name: Docker Image CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file src/Dockerfile --tag app_image:$(date +%s)
